name: build-binaries
on:
  workflow_dispatch: {}
  push:
    tags: ["v*"]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build .so
        run: |
          mkdir -p build
          cc -O2 -fPIC -Iinclude -c core/c/astra512.c -o build/astra512.o
          cc -shared -o build/libastra512.so build/astra512.o
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libastra512-linux
          path: build/libastra512.so

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build universal .dylib (arm64 + x86_64)
        run: |
          mkdir -p build
          clang -O2 -fPIC -arch x86_64 -arch arm64 -Iinclude -c core/c/astra512.c -o build/astra512.o
          clang -dynamiclib -arch x86_64 -arch arm64 -o build/libastra512.dylib build/astra512.o
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libastra512-macos-universal
          path: build/libastra512.dylib

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .def for exports
        shell: pwsh
        run: |
          @"
          LIBRARY astra512
          EXPORTS
            astra512_encrypt
            astra512_decrypt
          "@ | Out-File -Encoding ASCII astra512.def
      - name: Build .dll
        shell: pwsh
        run: |
          mkdir build
          cl /O2 /LD /I include core\c\astra512.c /link /DEF:astra512.def /OUT:build\astra512.dll
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: astra512-windows-x64
          path: build/astra512.dll

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [linux, macos, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { name: libastra512-linux, path: dist }
      - uses: actions/download-artifact@v4
        with: { name: libastra512-macos-universal, path: dist }
      - uses: actions/download-artifact@v4
        with: { name: astra512-windows-x64, path: dist }
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/libastra512.so
            dist/libastra512.dylib
            dist/astra512.dll
