name: build-binaries
on:
  workflow_dispatch: {}
  push:
    tags: ["v*"]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build .so (Linux)
        run: |
          mkdir -p native/build
          cc -O2 -fPIC -Inative/include -c native/core/c/astra512.c -o native/build/astra512.o
          cc -shared -o native/build/libastra512.so native/build/astra512.o
      - uses: actions/upload-artifact@v4
        with:
          name: libastra512-linux
          path: native/build/libastra512.so

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build universal .dylib (arm64 + x86_64)
        run: |
          mkdir -p native/build
          clang -O2 -fPIC -arch x86_64 -arch arm64 -Inative/include -c native/core/c/astra512.c -o native/build/astra512.o
          clang -dynamiclib -arch x86_64 -arch arm64 -o native/build/libastra512.dylib native/build/astra512.o
      - uses: actions/upload-artifact@v4
        with:
          name: libastra512-macos-universal
          path: native/build/libastra512.dylib

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .def for exports
        shell: pwsh
        run: |
          @"
          LIBRARY astra512
          EXPORTS
            astra512_encrypt
            astra512_decrypt
          "@ | Out-File -Encoding ASCII native\astra512.def
      - name: Build .dll (MSVC)
        shell: pwsh
        run: |
          mkdir native\build
          cl /O2 /LD /I native\include native\core\c\astra512.c /link /DEF:native\astra512.def /OUT:native\build\astra512.dll
      - uses: actions/upload-artifact@v4
        with:
          name: astra512-windows-x64
          path: native/build/astra512.dll

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [linux, macos, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { name: libastra512-linux, path: dist }
      - uses: actions/download-artifact@v4
        with: { name: libastra512-macos-universal, path: dist }
      - uses: actions/download-artifact@v4
        with: { name: astra512-windows-x64, path: dist }
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/libastra512.so
            dist/libastra512.dylib
            dist/astra512.dll
